---
title: Julia Brumfield Diaries
email: benwbrum@gmail.com
owner: Ben W. Brumfield
description: "<p>Julia Ann Craddock Brumfield kept a diary from 1915 until 1936.  Some
  time after her death, those diaries were distributed among her many grandchildren.
  \ Over the last twenty years, nearly half of those diaries have been reassembled
  to be shared among Julia's descendants.  The project is actively seeking other copies
  of these diaries.</p>\r\n\r\n<p>Scanning of the diaries has been performed by Mark
  Trenchard and Ben Brumfield.  Transcription has been by many volunteers, especially
  including Linda Tucker and Neil Brumfield.  Editing has been performed by Ben Brumfield.</p>\r\n"
plugins:
- jekyll-feed
- jekyll-remote-theme
- jekyll-include-cache
remote_theme: mmistakes/minimal-mistakes
defaults:
- scope:
    path: ''
  values:
    layout: archive
